### ISSUE TITLE
Error in install with berkshelf

### ISSUE THREAD

**Issue by meganuke19** [TD-4242/zabbix-agent#13]
Hello.

My Berksfile 
```
source "https://api.berkshelf.com"
cookbook "zabbix-agent", "~> 0.13.0"
```
i try execute `berks install` but receive this error:
`There is a circular dependency between libzabbix and zabbix-agent
Unable to find a solution for demands: zabbix-agent (~> 0.13.0)`
How i can resolve this problem?

**Comment by TD-4242** [comment]
Hmm, looks like I need to update the Berksfile anyway.

remove the zabbix-agent line from the Berksfile.

**Comment by TD-4242** [comment]
this should be fixed.

**Comment by JimWatV1** [comment]
I am still getting this, even adding cookbook 'zabbix-agent', "~> 0.13.3" to my Berksfile.  The versions in my Berks cache are zabbix-agent-0.13.3 and libzabbix-0.1.0 Do I need something newer?
